In [4]:
import numpy as np
import pandas as pd
from numpy.linalg import eigh,norm

In [5]:
df = pd.read_csv("iris.data")
df = df.replace(to_replace=["Iris-setosa","Iris-versicolor","Iris-virginica"],value=[0,1,2])
features = df[df.columns[:-1]] 


In [15]:
ndarray = features.to_numpy()
ndarray

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [16]:
ndarray.T@ndarray


array([[5223.85, 2670.98, 3484.25, 1127.65],
       [2670.98, 1427.05, 1673.91,  531.53],
       [3484.25, 1673.91, 2583.  ,  868.97],
       [1127.65,  531.53,  868.97,  302.3 ]])

In [18]:
eigen_value, eigen_vector = eigh(ndarray.T@ndarray)

In [20]:
eigen_vector

array([[ 0.32345496,  0.49942378,  0.28583096, -0.75116805],
       [-0.32124324, -0.67502499,  0.54488976, -0.37978837],
       [-0.48077482, -0.05471983, -0.70889874, -0.51315094],
       [ 0.74902286, -0.54029889, -0.34475845, -0.16787934]])

In [24]:
u0 = ndarray@eigen_vector[:,0]/norm(ndarray@eigen_vector[:,0])
u1 = ndarray@eigen_vector[:,1]/norm(ndarray@eigen_vector[:,1])
u2 = ndarray@eigen_vector[:,2]/norm(ndarray@eigen_vector[:,2])
u3 = ndarray@eigen_vector[:,3]/norm(ndarray@eigen_vector[:,3])

In [26]:
U = np.array([u0,u1,u2,u3]).T
print(U)

[[ 1.05847972e-03 -5.58364155e-05  1.29969428e-01 -6.16171172e-02]
 [ 5.21149461e-02  6.84386629e-02  1.11371452e-01 -5.80722977e-02]
 [ 9.07826254e-03  2.31062793e-03  1.18294769e-01 -5.67633852e-02]
 [-4.22153145e-02  4.21768760e-03  1.05607729e-01 -5.66543140e-02]
 [-3.32538281e-02 -3.39084839e-02  1.31431142e-01 -6.12300644e-02]
 [-1.27200659e-02 -7.05769279e-02  1.31215489e-01 -6.75033389e-02]
 [-2.80545702e-02 -6.81501228e-02  1.16885813e-01 -5.74819200e-02]
 [-2.46471653e-02  3.42848316e-03  1.21282279e-01 -6.09732389e-02]
 [-1.68628083e-02  1.59181065e-02  1.00233102e-01 -5.37621363e-02]
 [-3.04349879e-02  6.29780195e-02  1.12391313e-01 -5.88279568e-02]
 [-7.07901605e-03  2.63927871e-03  1.36956828e-01 -6.52921638e-02]
 [-8.46651181e-02 -2.69398447e-02  1.14056843e-01 -5.99423079e-02]
 [-4.96476881e-03  6.96168589e-02  1.11703944e-01 -5.71144645e-02]
 [-1.42760246e-02  2.37096865e-03  1.15639752e-01 -5.15956982e-02]
 [ 8.72529293e-02  6.58185398e-03  1.64631050e-01 -6.80066676e

In [27]:
sigma = np.round(U.T@ndarray@eigen_vector, decimals=5)
print(sigma)

[[ 1.87891 -0.      -0.      -0.     ]
 [-0.       3.4693  -0.       0.     ]
 [-0.      -0.      17.72295 -0.     ]
 [-0.       0.      -0.      95.95067]]
